package graphingcalculator3d.client.gui;

import com.mojang.blaze3d.vertex.PoseStack;
import graphingcalculator3d.common.GraphingCalculator3D;
import graphingcalculator3d.common.gameplay.tile.TileGCBase;
import graphingcalculator3d.common.util.config.ConfigVars;
import graphingcalculator3d.common.util.math.expression.EvalInfo;
import graphingcalculator3d.common.util.math.expression.Evaluations;
import graphingcalculator3d.common.util.math.expression.Expression;
import graphingcalculator3d.common.util.math.expression.Expression.Evaluation;
import graphingcalculator3d.common.util.nbthandler.Domain;
import graphingcalculator3d.common.util.networking.GCPacketHandler;
import graphingcalculator3d.common.util.networking.packets.PacketGC;
import net.minecraft.client.gui.components.AbstractWidget;
import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.components.EditBox;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.phys.Vec3;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.api.distmarker.OnlyIn;
import org.apache.commons.lang3.ArrayUtils;
import org.joml.Vector3d;
import org.lwjgl.glfw.GLFW;

import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.InputMismatchException;
import java.util.Scanner;

@OnlyIn(Dist.CLIENT)
public class GuiGC extends Screen {
    static final ResourceLocation CALC_BACK = ResourceLocation.fromNamespaceAndPath(GraphingCalculator3D.MODID, "textures/gui/calc_back.png");

    static final String FUNCTION = "Function: String form of a function. Automatically generated by the equation blocks. You can copy-paste this into a different calculator"
            + " if you don't want to copy all the other settings with a memory card item.";
    static final String DOMAINA = "A-Domain: The lower and upper boundaries of the function's A-values.";
    static final String DOMAINB = "B-Domain: The lower and upper boundaries of the function's B-values";
    static final String RANGE = "Range: The lower and upper boundaries of the function's outputs";
    static final String RESOLUTION = "Resolution: The number of points per 1 unit.";
    static final String SCALE = "X-Scale, Y-Scale, Z-Scale: Use this to expand or shrink the graph.";
    static final String TEX = "Texture: The image to stitch onto the graph.";
    static final String RGBA = "RGBA Values, Color Slope?, Transparancy Mode: Red, Green, Blue, Alpha (Opacity), Color graph to reflect slope?, Transparency Mode. Input \"r\" for a random selection. Transparancy Modes:"
            + " 0 = Auto, 1 = Fast, 2 = Fancy.";
    static final String CROP = "Crop function to range?: If true, will crop values exceeding the range to the range. If false, those values will not be displayed.";
    static final String DISCTHRESH = "Discontinuity Threshold, Aggressive Discontinuity Threshold: Slopes exceeding the first value will be considered discontinuous, and will not be displayed. If the second value is greater than 0, scaled absolute distances between points"
            + " greater than the second value will not be displayed (useful for cleaning up Bipolar Cylindrical graphs, as an example).";
    static final String TILECOUNT = "Tile Count: The positive integer number of segments over which one (1) texture tile is spread.";
    static final String TRANSLATION = "Translation: Offset in blocks from the origin.";
    static final String ROTATION = "Rotation: Rotation in degrees around the X, Y, and Z axis.";
    static final String COLLISION = "Collide?: Whether or not the graph is collidable.";

    static final String PIO4 = "Value of pi/4 for all your copy-paste needs.";
    static final String PIO2 = "Value of pi/2 for all your copy-paste needs.";
    static final String PI = "Value of pi for all your copy-paste needs.";
    static final String PI2 = "Value of 2pi for all your copy-paste needs.";
    static final String PI4 = "Value of 4pi for all your copy-paste needs.";
    static final String EO2 = "Value of e/2 for all your copy-paste needs.";
    static final String E = "Value of e for all your copy-paste needs.";
    static final String E2 = "Value of 2e for all your copy-paste needs.";

    static final String VAL = "Value to put into value block. Shift + Click while hovering over the value block to fill it with this value. Special values can be inputtet as well."
            + " The list of special values is as follows: pi, e, a, b, c, gold_r, plank_c, grav_c, boltz_c, avog_c. The values a, b, and c are defined in the config, while the rest"
            + " are mathematical constants. Some of them might not be useful for graphing purposes, but I included them anyway, so deal with it.";
    static final String DELETE_SECTION = "Drop a block here to delete it.";

    static final String DONE = "Done";
    static final String UNDELETE = "Undelete Block";
    static final String NEXT = "--->";
    static final String PREV = "<---";

    int id = 0;

    protected final ArrayList<AbstractWidget> buttons = new ArrayList<>();
    HashMap<EditBox, String> fieldToString = new HashMap<>();

    public Expression expression;
    public TileGCBase tile;
    private int erroredBox;

    protected boolean dragging = false;
    protected ExpressionBlock draggedBlock;
    protected boolean modified = false;
    protected boolean tooltipDrawing = false;
    protected String currentTooltip = "";

    public Section spawnSection;
    public Section deleteSection;
    private final ArrayList<ExpressionBlock> deleteList = new ArrayList<>();
    int pageInd = 0;
    int maxPage;

    int guiX = 0;
    int guiY = 0;
    int guiWidth = 0;
    int guiHeight = 0;
    int fieldWidth = 160;
    int blockSpawnY = 210;
    TextButton done;
    TextButton next;
    TextButton prev;
    TextButton undelete;

    EditBox function;
    DomainTextField domainA;
    DomainTextField domainB;
    DomainTextField range;
    EditBox resolution;
    Vec3dTextField scale;
    EditBox tex;
    ColorTextField rgba;
    EditBox cropToRange;
    DiscContinutityTextField discThresh;
    EditBox tileCount;
    Vec3dTextField translation;
    Vec3dTextField rotation;
    EditBox collision;

    EditBox piO4;
    EditBox piO2;
    EditBox pi;
    EditBox pi2;
    EditBox pi4;
    EditBox eO2;
    EditBox e;
    EditBox e2;

    EditBox valField;

    EditBox[] textFields = new EditBox[]{};

    VisibleImage background;
    NumberFormat f = NumberFormat.getInstance();

    public GuiGC(TileGCBase tile) {
        super(Component.literal("Graphing Calculator"));
        this.tile = tile;
    }

    private EditBox field(int x, int y, int width, int height) {
        return new EditBox(this.font, x, y, width, height, Component.empty());
    }

    @Override
    protected void init() {
        super.init();

        buttons.clear();

        guiWidth = (int) (this.width / 1.01);
        guiHeight = (int) (this.height / 1.01);

        guiX = SetupGui.centerVal(0, width, guiWidth);
        guiY = SetupGui.centerVal(0, height, guiHeight);

        background = new VisibleImage(guiX, guiY, CALC_BACK, true, guiWidth, guiHeight);

        done = new TextButton(guiX + guiWidth - 33, guiY + 135 + 3, font.width(DONE), font.lineHeight, DONE, this::done);

        function = field(guiX + 3, guiY + 3, guiWidth - 6, done.defaultHeight);
        domainA = new DomainTextField("X-Domain", this, font, guiX + 3, guiY + 15 + 3, fieldWidth, done.defaultHeight, tile::setDomainA);
        range = new DomainTextField("Range", this, font, guiX + 3, guiY + 30 + 3, fieldWidth, done.defaultHeight, tile::setRange);
        domainB = new DomainTextField("Z-Domain", this, font, guiX + 3, guiY + 45 + 3, fieldWidth, done.defaultHeight, tile::setDomainB);
        resolution = field(guiX + 3, guiY + 60 + 3, fieldWidth, done.defaultHeight);
        rgba = new ColorTextField(this, font, guiX + 3, guiY + 75 + 3, fieldWidth, done.defaultHeight);
        tex = field(guiX + 3, guiY + 90 + 3, fieldWidth, done.defaultHeight);
        tileCount = field(guiX + 3, guiY + 105 + 3, fieldWidth, done.defaultHeight);
        cropToRange = field(guiX + 3, guiY + 120 + 3, fieldWidth, done.defaultHeight);
        discThresh = new DiscContinutityTextField(this, font, guiX + 3, guiY + 135 + 3, fieldWidth, done.defaultHeight);
        scale = new Vec3dTextField("Scale", this, font, guiX + 3, guiY + 150 + 3, fieldWidth, done.defaultHeight, vec -> tile.scale = vec);
        translation = new Vec3dTextField("Translation", this, font, guiX + 3, guiY + 165 + 3, fieldWidth, done.defaultHeight, vec -> tile.translation = vec);
        rotation = new Vec3dTextField("Rotation", this, font, guiX + 3, guiY + 180 + 3, fieldWidth, done.defaultHeight, vec -> tile.rotation = vec);
        collision = field(guiX + 3, guiY + 195 + 3, fieldWidth, done.defaultHeight);

        piO4 = field(guiX + guiWidth - 33, guiY + 15 + 3, 30, done.defaultHeight);
        piO2 = field(guiX + guiWidth - 33, guiY + 30 + 3, 30, done.defaultHeight);
        pi = field(guiX + guiWidth - 33, guiY + 45 + 3, 30, done.defaultHeight);
        pi2 = field(guiX + guiWidth - 33, guiY + 60 + 3, 30, done.defaultHeight);
        pi4 = field(guiX + guiWidth - 33, guiY + 75 + 3, 30, done.defaultHeight);
        eO2 = field(guiX + guiWidth - 33, guiY + 90 + 3, 30, done.defaultHeight);
        e = field(guiX + guiWidth - 33, guiY + 105 + 3, 30, done.defaultHeight);
        e2 = field(guiX + guiWidth - 33, guiY + 120 + 3, 30, done.defaultHeight);

        spawnSection = new Section(guiX + fieldWidth + 6, guiY + 15 + 2, piO4.getX() - 3 - guiX - fieldWidth - 6, 117);
        deleteSection = new Section(guiX + guiWidth - 20 - 3, guiY + guiHeight - 20 - 3, 20, 20);

        int tempX = 3;
        int tempY = 3;
        int tempPage = 0;
        for (Evaluation current : Evaluations.ordered) {
            if (current == null)
                continue;
            EvalInfo info = Evaluations.infoMap.get(current);
            if (info == null)
                continue;
            BlockSpawner spawn = new BlockSpawner(id++, 0, 0, info.string, info.slots, info.eval, this, info.rgb[0], info.rgb[1], info.rgb[2])
                    .setOnPage(true);
            ExpressionBlock block = spawn.spawn(id++);
            block.arrange(0, 0);
            if (spawnSection.x + tempX + block.getWidth() + 3 > spawnSection.right) {
                tempX = 3;
                tempY = tempY + block.getHeight() + 3;
            }
            if (spawnSection.y + tempY + block.getHeight() + 3 >= spawnSection.down) {
                tempY = 3;
                tempPage++;
            }
            spawn.setPage(tempPage);
            spawn.setX(spawnSection.x + tempX);
            spawn.setY(spawnSection.y + tempY);
            block.arrange(spawnSection.x + tempX, spawnSection.y + tempY);
            block.page = spawn.page;
            if (block.page != 0)
                block.visible = false;
            tempX = tempX + block.getWidth() + 3;
        }
        maxPage = tempPage;

        if (tile.getFunction() != null) {
            ExpressionBlock tempBlock = ExpressionBlock.blockFromExpression(id++, tile.getFunction(), this);
            id = tempBlock.gennedID;
            tempBlock.arrange(guiX + 3, guiY + blockSpawnY + 3);
            tempBlock.setMoved(true);
        }

        valField = field(spawnSection.x + (spawnSection.width / 2) - 15, spawnSection.down + 3, 30, done.defaultHeight);

        next = new TextButton(valField.getX() + valField.getWidth() + 3, valField.getY(), font.width(NEXT), font.lineHeight, NEXT, () -> changePage(1));
        prev = new TextButton(valField.getX() - font.width(PREV) - 3, valField.getY(), font.width(PREV),
                font.lineHeight, PREV, () -> changePage(-1));
        undelete = new TextButton((int) (valField.getX() + (0.5 * valField.getWidth()) - (0.5 * font.width(UNDELETE))),
                valField.getY() + 14, font.width(UNDELETE), font.lineHeight, UNDELETE, this::unDeleteBlock);

        done.visible = true;
        next.visible = true;
        prev.visible = true;
        undelete.visible = true;

        fieldToString.clear();
        fieldToString.put(function, FUNCTION);
        fieldToString.put(domainA, DOMAINA);
        fieldToString.put(domainB, DOMAINB);
        fieldToString.put(range, RANGE);
        fieldToString.put(resolution, RESOLUTION);
        fieldToString.put(scale, SCALE);
        fieldToString.put(tex, TEX);
        fieldToString.put(rgba, RGBA);
        fieldToString.put(cropToRange, CROP);
        fieldToString.put(discThresh, DISCTHRESH);
        fieldToString.put(tileCount, TILECOUNT);
        fieldToString.put(translation, TRANSLATION);
        fieldToString.put(rotation, ROTATION);
        fieldToString.put(valField, VAL);
        fieldToString.put(collision, COLLISION);

        fieldToString.put(piO4, PIO4);
        fieldToString.put(piO2, PIO2);
        fieldToString.put(pi, PI);
        fieldToString.put(pi2, PI2);
        fieldToString.put(pi4, PI4);
        fieldToString.put(eO2, EO2);
        fieldToString.put(e, E);
        fieldToString.put(e2, E2);

        textFields = new EditBox[]{};
        textFields = ArrayUtils.add(textFields, function);
        textFields = ArrayUtils.add(textFields, domainA);
        textFields = ArrayUtils.add(textFields, range);
        textFields = ArrayUtils.add(textFields, domainB);
        textFields = ArrayUtils.add(textFields, resolution);
        textFields = ArrayUtils.add(textFields, rgba);
        textFields = ArrayUtils.add(textFields, tex);
        textFields = ArrayUtils.add(textFields, tileCount);
        textFields = ArrayUtils.add(textFields, cropToRange);
        textFields = ArrayUtils.add(textFields, discThresh);
        textFields = ArrayUtils.add(textFields, scale);
        textFields = ArrayUtils.add(textFields, translation);
        textFields = ArrayUtils.add(textFields, rotation);
        textFields = ArrayUtils.add(textFields, valField);
        textFields = ArrayUtils.add(textFields, collision);

        textFields = ArrayUtils.add(textFields, piO4);
        textFields = ArrayUtils.add(textFields, piO2);
        textFields = ArrayUtils.add(textFields, pi);
        textFields = ArrayUtils.add(textFields, pi2);
        textFields = ArrayUtils.add(textFields, pi4);
        textFields = ArrayUtils.add(textFields, eO2);
        textFields = ArrayUtils.add(textFields, e);
        textFields = ArrayUtils.add(textFields, e2);

        for (EditBox field : textFields) {
            field.visible = true;
            field.setMaxLength(1500);
        }

        if (tile.isErrored())
            function.setValue(tile.getErroredFunction());
        if (tile.getFunction() != null)
            function.setValue(tile.getFunction().writeToString());

        f.setMaximumFractionDigits(ConfigVars.GraphingConfigs.decPlaces);

        domainA.setValue(format(f, tile.getDomainA()));
        domainB.setValue(format(f, tile.getDomainB()));
        range.setValue(format(f, tile.getRange()));

        resolution.setValue(f.format(tile.getResolution()));
        scale.setValue(format(f, tile.scale));
        tex.setValue(tile.tex);
        rgba.setValue(tile.rgba[0] + " " + tile.rgba[1] + " " + tile.rgba[2] + " " + tile.rgba[3] + " " + tile.colorSlope + " " + tile.rgba[4]);
        cropToRange.setValue("" + tile.cropToRange());
        discThresh.setValue(f.format(tile.getDiscThresh()) + " " + f.format(tile.getAggDiscThresh()));
        tileCount.setValue("" + tile.tileCount);
        translation.setValue(format(f, tile.translation));
        rotation.setValue(format(f, tile.rotation.mul(180 / Math.PI)));
        collision.setValue("" + tile.collision);

        piO4.setValue(f.format(Math.PI / 4));
        piO2.setValue(f.format(Math.PI / 2));
        pi.setValue(f.format(Math.PI));
        pi2.setValue(f.format(2 * Math.PI));
        pi4.setValue(f.format(4 * Math.PI));
        eO2.setValue(f.format(Math.E / 2));
        e.setValue(f.format(Math.E));
        e2.setValue(f.format(2 * Math.E));

        valField.setValue("");

        domainA.setCursorPosition(0);
        domainB.setCursorPosition(0);
        tex.setCursorPosition(0);

        piO4.setCursorPosition(0);
        piO2.setCursorPosition(0);
        pi.setCursorPosition(0);
        pi2.setCursorPosition(0);
        pi4.setCursorPosition(0);
        eO2.setCursorPosition(0);
        e.setCursorPosition(0);
        e2.setCursorPosition(0);

        function.setFocused(true);

        button(done);
        button(next);
        button(prev);
        button(undelete);

        updateBlockStrings();
    }

    private static String format(NumberFormat f, Domain domain) {
        return f.format(domain.min()) + " " + f.format(domain.max());
    }

    private static String format(NumberFormat f, Vector3d vec3d) {
        return f.format(vec3d.x) + " " + f.format(vec3d.y) + " " + f.format(vec3d.z);
    }

    @Override
    public void render(PoseStack poseStack, int mouseX, int mouseY, float renderPartials) {
        modified = false;
        background.draw(poseStack);
        spawnSection.drawSection(poseStack, 40, 40, 40);
        deleteSection.drawSection(poseStack, 255, 0, 0);
        for (EditBox field : textFields) {
            field.render(poseStack, mouseX, mouseY, renderPartials);
        }

        for (AbstractWidget current : buttons) {
            current.render(poseStack, mouseX, mouseY, renderPartials);
        }

        if (tile.isErrored()) {
            Component error = Component.literal("Error: " + tile.getErrorMessage());
            font.drawWordWrap(poseStack, error, guiX + 3,
                    guiY + guiHeight - 1 - font.wordWrapHeight(error, guiWidth - deleteSection.width - 9),
                    guiWidth - deleteSection.width - 9, 0xFF0000);
            EditBox erroredField = textFields[erroredBox];
            Section sec = new Section(erroredField.getX(), erroredField.getY(), erroredField.getWidth(), erroredField.getHeight());
            sec.drawSection(poseStack, 255, 0, 0, 100);
        }

        if (dragging)
            draggedBlock.render(poseStack, mouseX, mouseY, renderPartials);

        for (EditBox current : textFields) {
            if (dragging)
                break;
            if (mouseX > current.getX() + current.getWidth() - 10 && mouseX < current.getX() + current.getWidth() && mouseY > current.getY() && mouseY < current.getY() + current.getHeight()) {
                renderTooltip(poseStack, Component.literal(fieldToString.get(current)), current.getX() + current.getWidth(), current.getY() + current.getHeight());
            }
        }

        for (AbstractWidget current : buttons) {
            if (dragging)
                break;
            if (current instanceof ExpressionBlock block) {

                if (block.whole(mouseX, mouseY) && !block.moved && block.visible) {
                    renderTooltip(poseStack, Component.literal(Evaluations.infoMap.get(block.expression.evaluation).tooltip), guiX - 7,
                            rotation.getY() + rotation.getHeight() + 15 + 5);
                }
            }
        }

        if (deleteSection.isPointWithinIncl(mouseX, mouseY))
            renderTooltip(poseStack, Component.literal(DELETE_SECTION), deleteSection.x, deleteSection.y);
    }

    @Override
    public void tick() {
        super.tick();
        Arrays.stream(textFields).forEach(EditBox::tick);
    }

    private void changePage(int delta) {
        pageInd += delta;

        if (pageInd > maxPage) {
            pageInd = 0;
        }
        if (pageInd < 0) {
            pageInd = maxPage;
        }

        updateExpressionBlockVisibility();
    }

    private void updateExpressionBlockVisibility() {
        for (AbstractWidget current : buttons) {
            if (current instanceof ExpressionBlock) {
                ExpressionBlock block = (ExpressionBlock) current;
                if (block.onPage) {
                    block.visible = (block.page == pageInd);
                }
            }
        }
    }

    @Override
    public boolean charTyped(char typedChar, int modifiers) {
        super.charTyped(typedChar, modifiers);

        for (EditBox field : textFields) {
            field.charTyped(typedChar, modifiers);
        }

        return true;
    }

    @Override
    public boolean keyPressed(int keyCode, int scanCode, int modifiers) {
        super.keyPressed(keyCode, scanCode, modifiers);

        for (EditBox field : textFields) {
            field.keyPressed(keyCode, scanCode, modifiers);
        }

        if (Screen.hasShiftDown()) {
            if (keyCode == GLFW.GLFW_KEY_TAB) {
                backOne();
            } else if (keyCode == GLFW.GLFW_KEY_DOWN) {
                forwardOne();
                forwardOne();
                forwardOne();
            } else if (keyCode == GLFW.GLFW_KEY_UP) {
                backOne();
                backOne();
                backOne();
            }
        } else if (Screen.hasAltDown()) {
            switch (keyCode) {
                case GLFW.GLFW_KEY_LEFT:
                    skipInTextField(-4);
                    break;
                case GLFW.GLFW_KEY_RIGHT:
                    skipInTextField(4);
                    break;
                default:
                    break;
            }
        } else if (keyCode == GLFW.GLFW_KEY_TAB || keyCode == GLFW.GLFW_KEY_DOWN) {
            forwardOne();
        } else if (keyCode == GLFW.GLFW_KEY_UP) {
            backOne();
        } else if (keyCode == GLFW.GLFW_KEY_ENTER || keyCode == GLFW.GLFW_KEY_KP_ENTER) {
            done();
        } else if (keyCode == GLFW.GLFW_KEY_R) {
            unDeleteBlock();
        }

        return true;
    }

    @Override
    public boolean mouseClicked(double mouseX, double mouseY, int mouseButton) {
        if (Screen.hasShiftDown()) {
            ExpressionBlock block = this.getBlockAt(mouseX, mouseY, true);
            if (block == null)
                return true;
            if (block.slots.length == 0 && block.expression.evaluation == Evaluations.VAL) {
                Scanner boxScan = new Scanner(valField.getValue());
                if (boxScan.hasNextDouble()) {
                    block.expression.setValueValue("" + boxScan.nextDouble(), false);
                } else if (boxScan.hasNext()) {
                    block.expression.setValueValue(boxScan.next(), true);
                }

                block.setMessage(Component.literal(block.expression.getValueValue()));
                block.arrange(block.getX(), block.getY());
                boxScan.close();
            }

            return true;
        } else if (Screen.hasControlDown() && !dragging) {
            ExpressionBlock clickedBlock = this.getBlockAt(mouseX, mouseY, true);
            if (clickedBlock == null)
                return false;
            ExpressionBlock dupedBlock = clickedBlock.duplicate(id++);
            id = clickedBlock.gennedID;
            dupedBlock.arrange(guiX + 3, guiY + 195 + 3);
            dupedBlock.setMoved(true);
            this.setDragging(dupedBlock);
            return true;
        } else if (Screen.hasAltDown() && !dragging) {
            ExpressionBlock clickedBlock = this.getBlockAt(mouseX, mouseY, true);
            if (clickedBlock == null || spawnSection.isPointWithinIncl(mouseX, mouseY))
                return false;
            deleteBlock(clickedBlock);
            return true;
        }

        for (EditBox field : textFields) {
            if (field.mouseClicked(mouseX, mouseY, mouseButton)) {
                return true;
            }
        }

        for (int i = buttons.size() - 1; i >= 0; i--) {
            if (buttons.get(i).mouseClicked(mouseX, mouseY, mouseButton)) {
                return true;
            }
        }

        return super.mouseClicked(mouseX, mouseY, mouseButton);
    }

    public void backOne() {
        for (int i = 0; i < textFields.length; i++)
            if (textFields[i].isFocused()) {
                textFields[i].setFocused(false);
                if (i - 1 >= 0)
                    textFields[i - 1].setFocused(true);
                else
                    textFields[textFields.length - 1].setFocused(true);
                break;
            }

    }

    public void forwardOne() {
        for (int i = 0; i < textFields.length; i++)
            if (textFields[i].isFocused()) {
                textFields[i].setFocused(false);
                if (i + 1 < textFields.length)
                    textFields[i + 1].setFocused(true);
                else
                    textFields[0].setFocused(true);
                break;
            }

    }

    public void skipInTextField(int chars) {
        for (EditBox textField : textFields) {
            if (textField.isFocused()) {
                textField.setCursorPosition(textField.getCursorPosition() + chars);
                break;
            }
        }
    }

    public void done() {
        int box = 0;
        try {
            tile.setErrored(false);
            tile.renderReady = false;
            expression = Expression.parseFromChars(function.getValue());
            tile.setFunctionText(function.getValue());
            ExpressionBlock block = null;
            if (unslottetBlockCount() > 1)
                setErrored("Loose equation blocks. Reduce the function to a single block.");
            block = this.getFunctionExpression();
            if (block != null) {
                tile.setFunction(block.getExpression());
            } else {
                tile.setFunction(expression);
            }
            box++;
            domainA.done();
            box++;
            range.done();
            box++;
            domainB.done();
            box++;
            tile.setResolution((float) Double.parseDouble(resolution.getValue().replaceAll(",", "")));
            box++;
            rgba.done();
            box++;
            tile.tex = tex.getValue();
            box++;
            tile.tileCount = Math.max(Integer.parseInt(tileCount.getValue().replaceAll(",", "")), 1);
            box++;
            tile.cropToRange(Boolean.parseBoolean(cropToRange.getValue()));
            box++;
            discThresh.done();
            box++;
            scale.done();
            box++;
            translation.done();
            box++;
            rotation.done();
            box++;
            tile.collision = Boolean.parseBoolean(collision.getValue());
            box++;

            tile.genMesh();
            minecraft.setScreen(null);

            GCPacketHandler.GRAPH_SYNC.sendToServer(new PacketGC(tile));
        } catch (NumberFormatException e) {
            tile.setErrored(true, "Invalid number formatting. Field #" + box);
            erroredBox = box;
            tile.setErroredFunction(function.getMessage().getString());
            e.printStackTrace();
        } catch (InputMismatchException e) {
            tile.setErrored(true, "Invalid boolean. Field #" + box);
            erroredBox = box;
            tile.setErroredFunction(function.getMessage().getString());
            e.printStackTrace();
        } catch (GuiParseException e) {
            tile.setErrored(true, tile.getErrorMessage() + " Field #" + box);
            erroredBox = box;
            tile.setErroredFunction(function.getMessage().getString());
            e.printStackTrace();
        }
    }

    public void button(AbstractWidget button) {
        buttons.add(button);
    }

    public void setDragging(ExpressionBlock block) {
        if (!modified) {
            if (dragging)
                return;
            dragging = true;
            draggedBlock = block;
            draggedBlock.dragged = true;
            draggedBlock.onPage = false;
            modified = true;
        }
    }

    public void blockDropped() {
        if (!modified) {
            if (spawnSection.isPointWithinIncl(draggedBlock.getX(), draggedBlock.getY()))
                return;
            dragging = false;
            draggedBlock.dragged = false;
            if (deleteSection.isPointWithinIncl(draggedBlock.getX(), draggedBlock.getY()))
                deleteBlock(draggedBlock);
            draggedBlock = null;
            modified = true;
        }
    }

    public void updateBlockStrings() {
        ExpressionBlock block = this.getFunctionExpression();
        if (block == null)
            return;
        Expression expr = block.getExpression();
        if (expr == null)
            return;

        expr.prepareSeries();

        for (AbstractWidget widget : buttons) {
            if (widget instanceof ExpressionBlock) {
                ExpressionBlock b = ((ExpressionBlock) widget);
                b.updateStringVars();
            }
        }
    }

    public boolean isSlotAt(int x, int y) {
        boolean b = false;
        for (AbstractWidget widget : buttons) {
            if (widget instanceof ExpressionBlock) {
                b = ((ExpressionBlock) widget).slotNotWhole(x, y);
                if (b)
                    return true;
            }
        }
        return false;
    }

    public ExpressionBlock getBlockAt(double x, double y, boolean excludeDragged) {
        ExpressionBlock temp = null;
        for (AbstractWidget widget : buttons) {
            if (widget instanceof ExpressionBlock)
                if (((ExpressionBlock) widget).wholeNotSlot(x, y) && (widget != draggedBlock || !excludeDragged) && widget.visible)
                    temp = (ExpressionBlock) widget;
        }

        return temp;
    }

    public ExpressionBlock getWholeBlockAt(int x, int y, boolean excludeDragged) {
        ExpressionBlock temp = null;
        for (AbstractWidget widget : buttons) {
            if (widget instanceof ExpressionBlock)
                if (((ExpressionBlock) widget).whole(x, y) && (widget != draggedBlock || !excludeDragged))
                    temp = (ExpressionBlock) widget;
        }
        return temp;
    }

    public boolean slottingReqAt(double x, double y) {
        for (AbstractWidget widget : buttons) {
            if (widget instanceof ExpressionBlock && widget != draggedBlock) {
                ExpressionBlock block = (ExpressionBlock) widget;
                if (!block.slotNotWhole(x, y))
                    continue;
                int s = block.getSlotNumAt(x, y);
                if (!block.slotFull(s)) {
                    block.setBlock(s, draggedBlock);
                    return true;
                }
            }
        }
        return false;
    }

    public ExpressionBlock getFunctionExpression() {
        for (AbstractWidget widget : buttons) {
            if (widget instanceof ExpressionBlock) {
                ExpressionBlock block = (ExpressionBlock) widget;
                if (!block.slotted && block.moved && block.visible)
                    return block;
            }
        }
        return null;
    }

    public void removeButton(Button button) {
        buttons.remove(button);
    }

    public void setTooltipDrawing(boolean drawing, String tipIn) {
        tooltipDrawing = drawing;
        currentTooltip = tipIn;
    }

    public int unslottetBlockCount() {
        int count = 0;
        for (AbstractWidget widget : buttons) {
            if (widget instanceof ExpressionBlock) {
                ExpressionBlock block = (ExpressionBlock) widget;
                if (!block.slotted && block.moved && block.visible)
                    count++;
            }
        }
        return count;
    }

    public void deleteBlock(ExpressionBlock block) {
        deleteList.add(block);
        block.delete(true);
    }

    public void unDeleteBlock() {
        if (!(deleteList.size() > 0))
            return;
        ExpressionBlock block = deleteList.get(deleteList.size() - 1);
        if (block != null) {
            block.unDelete();
            block.arrange(block.getX(), block.getY());
            block.setMoved(true);
            deleteList.remove(block);
        }
    }

    public void setErrored(String errorMessage) throws GuiParseException {
        tile.setErrored(true, errorMessage);
        throw new GuiParseException(errorMessage);
    }
}
