package graphingcalculator3d.client.gui;

import graphingcalculator3d.common.GraphingCalculator3D;
import graphingcalculator3d.common.gameplay.tile.TileGCBase;
import graphingcalculator3d.common.util.config.ConfigVars;
import graphingcalculator3d.common.util.math.expression.EvalInfo;
import graphingcalculator3d.common.util.math.expression.Evaluations;
import graphingcalculator3d.common.util.math.expression.Expression;
import graphingcalculator3d.common.util.math.expression.Expression.Evaluation;
import graphingcalculator3d.common.util.nbthandler.Domain;
import graphingcalculator3d.common.util.networking.GCPacketHandler;
import graphingcalculator3d.common.util.networking.packets.PacketGC;
import net.minecraft.client.gui.screen.Screen;
import net.minecraft.client.gui.widget.TextFieldWidget;
import net.minecraft.client.gui.widget.Widget;
import net.minecraft.client.gui.widget.button.Button;
import net.minecraft.util.ResourceLocation;
import net.minecraft.util.math.MathHelper;
import net.minecraft.util.math.Vec3d;
import net.minecraft.util.text.ITextComponent;
import net.minecraft.util.text.StringTextComponent;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.api.distmarker.OnlyIn;
import org.apache.commons.lang3.ArrayUtils;

import java.text.NumberFormat;
import java.util.*;
import java.util.function.Consumer;

@OnlyIn(Dist.CLIENT)
public class GuiGC extends Screen {
    static final ResourceLocation CALC_BACK = new ResourceLocation(GraphingCalculator3D.MODID + ":textures/gui/calc_back.png");
	
	/*static final String FUNCTION = "Function: String form of a function. The syntax is as follows: Number of expressions within, evaluation to perform on inner expressions, inner expressions."
			+ " To express a value such as x, z, or 10, use 0VAL([j,k]), where 'j' is the constant or variable, and 'k' states whether 'j' is a variable or not."
			+ " Here is a simple example: 0VAL([x,1]) | Another example: 2MAX(1COS(0VAL([phi,1]))1SIN(0VAL([nu,1]))) | Another example: 2ADD(1SQR(0VAL([2,0]))1SIN(0VAL([phi,1])))"
			+ " You can input special numbers this way, too. For example: 1SINH(0VAL([pi,1])) | Another example: 1SQR_PRSRV(2ADD(0VAL([1,0])0VAL([e,1])))"
			+ " The list of special numbers is as follows: pi, e, a, b, c, gold_r, plank_c, grav_c, boltz_c, avog_c. a, b, and c refer to the variables of those names as defined in the config."
			+ " The list of evaluations is as follows: 2ADD, 2SUB, 1NEG, 2MULT, 1TWICE, 1HALF, 2DIVI, 1ONE_OVR, 1PERCENT, 1SQR, 1SQR_PRSRV, 1SQRT, 1SQRT_POS, 1SQRT_PRSRV, 2PWR, 2PWR_POS, 2PWR_PRSRV, 2ROOT, 2ROOT_POS, 2ROOT_PRSRV, 1EXPONENT, 2REM, 1ABS_VAL, 1SIN, 1COS, 1TAN, 1CSC"
			+ ", 1SEC, 1COT, 1SINH, 1COSH, 1TANH, 1ASIN, 1ACOS, 1ATAN, 1LN, 1LN_POS, 1LN_PRSRV, 1LOG, 1LOG_POS, 1LOG_PRSRV, 1LOG1P, 1INT, 1CEIL, 1FLOOR, 2HYPOT, 2MAX, 2MIN, 1RAN_INT, 2RAN_INT_BTWN, 1RAN_DOUB, 2RAN_DOUB_BTWN, 0RAN_GAUS."
			+ "If you have a suggested addition to anything, I'd be happy to implement it.";*/

    static final String FUNCTION = "Function: String form of a function. Automatically generated by the equation blocks. You can copy-paste this into a different calculator"
            + " if you don't want to copy all the other settings with a memory card item.";
    static final String DOMAINA = "A-Domain: The lower and upper boundaries of the function's A-values.";
    static final String DOMAINB = "B-Domain: The lower and upper boundaries of the function's B-values";
    static final String RANGE = "Range: The lower and upper boundaries of the function's outputs";
    static final String RESOLUTION = "Resolution: The number of points per 1 unit.";
    static final String SCALE = "X-Scale, Y-Scale, Z-Scale: Use this to expand or shrink the graph.";
    static final String TEX = "Texture: The image to stitch onto the graph.";
    static final String RGBA = "RGBA Values, Color Slope?, Transparancy Mode: Red, Green, Blue, Alpha (Opacity), Color graph to reflect slope?, Transparency Mode. Input \"r\" for a random selection. Transparancy Modes:"
            + " 0 = Auto, 1 = Fast, 2 = Fancy.";
    static final String CROP = "Crop function to range?: If true, will crop values exceeding the range to the range. If false, those values will not be displayed.";
    static final String DISCTHRESH = "Discontinuity Threshold, Aggressive Discontinuity Threshold: Slopes exceeding the first value will be considered discontinuous, and will not be displayed. If the second value is greater than 0, scaled absolute distances between points"
            + " greater than the second value will not be displayed (useful for cleaning up Bipolar Cylindrical graphs, as an example).";
    static final String TILECOUNT = "Tile Count: The positive integer number of segments over which one (1) texture tile is spread.";
    static final String TRANSLATION = "Translation: Offset in blocks from the origin.";
    static final String ROTATION = "Rotation: Rotation in degrees around the X, Y, and Z axis.";
    static final String COLLISION = "Collide?: Whether or not the graph is collidable.";

    static final String PIO4 = "Value of pi/4 for all your copy-paste needs.";
    static final String PIO2 = "Value of pi/2 for all your copy-paste needs.";
    static final String PI = "Value of pi for all your copy-paste needs.";
    static final String PI2 = "Value of 2pi for all your copy-paste needs.";
    static final String PI4 = "Value of 4pi for all your copy-paste needs.";
    static final String EO2 = "Value of e/2 for all your copy-paste needs.";
    static final String E = "Value of e for all your copy-paste needs.";
    static final String E2 = "Value of 2e for all your copy-paste needs.";

    static final String VAL = "Value to put into value block. Shift + Click while hovering over the value block to fill it with this value. Special values can be inputtet as well."
            + " The list of special values is as follows: pi, e, a, b, c, gold_r, plank_c, grav_c, boltz_c, avog_c. The values a, b, and c are defined in the config, while the rest"
            + " are mathematical constants. Some of them might not be useful for graphing purposes, but I included them anyway, so deal with it.";
    static final String DELETE_SECTION = "Drop a block here to delete it.";

    static final String DONE = "Done";
    static final String UNDELETE = "Undelete Block";
    static final String NEXT = "--->";
    static final String PREV = "<---";

    int id = 0;

    HashMap<TextFieldWidget, String> fieldToString = new HashMap<TextFieldWidget, String>();

    public Expression expression;
    public TileGCBase tile;
    private int erroredBox;

    protected boolean dragging = false;
    protected ExpressionBlock draggedBlock;
    protected boolean modified = false;
    protected boolean tooltipDrawing = false;
    protected String currentTooltip = "";

    public Section spawnSection;
    public Section deleteSection;
    private final ArrayList<ExpressionBlock> deleteList = new ArrayList<ExpressionBlock>();
    int pageInd = 0;
    int maxPage;

    int guiX = 0;
    int guiY = 0;
    int guiWidth = 0;
    int guiHeight = 0;
    int fieldWidth = 160;
    int blockSpawnY = 210;
    TextButton done;
    TextButton next;
    TextButton prev;
    TextButton undelete;

    TextFieldWidget function;
    DomainTextField domainA;
    DomainTextField domainB;
    DomainTextField range;
    TextFieldWidget resolution;
    Vec3dTextField scale;
    TextFieldWidget tex;
    ColorTextField rgba;
    TextFieldWidget cropToRange;
    DiscContinutityTextField discThresh;
    TextFieldWidget tileCount;
    Vec3dTextField translation;
    Vec3dTextField rotation;
    TextFieldWidget collision;

    TextFieldWidget piO4;
    TextFieldWidget piO2;
    TextFieldWidget pi;
    TextFieldWidget pi2;
    TextFieldWidget pi4;
    TextFieldWidget eO2;
    TextFieldWidget e;
    TextFieldWidget e2;

    TextFieldWidget valField;

    TextFieldWidget[] textFields = new TextFieldWidget[]{};

    VisibleImage background;
    NumberFormat f = NumberFormat.getInstance();

    public GuiGC(TileGCBase tile) {
        super(new StringTextComponent(""));
        this.tile = tile;
    }

    @Override
    public void init() {
        minecraft.getTextureManager().bindTexture(CALC_BACK);

        guiWidth = (int) (this.width / 1.01);
        guiHeight = (int) (this.height / 1.01);

        guiX = SetupGui.centerVal(0, width, guiWidth);
        guiY = SetupGui.centerVal(0, height, guiHeight);

        background = new VisibleImage(guiX, guiY, CALC_BACK, true, guiWidth, guiHeight);

        done = new TextButton(++id, guiX + guiWidth - 33, guiY + 135 + 3, font.getStringWidth(DONE), font.FONT_HEIGHT, DONE, this::done);

        function = new TextFieldWidget(font, ++id, guiX + 3, guiY + 3, guiWidth - 6 /*done.defaultHeight*/, "");
        domainA = new DomainTextField("X-Domain", this, ++id, minecraft.fontRenderer, guiX + 3, guiY + 15 + 3, fieldWidth, done.defaultHeight, tile::setDomainA);
        range = new DomainTextField("Range", this, ++id, minecraft.fontRenderer, guiX + 3, guiY + 30 + 3, fieldWidth, done.defaultHeight, tile::setRange);
        domainB = new DomainTextField("Z-Domain", this, ++id, minecraft.fontRenderer, guiX + 3, guiY + 45 + 3, fieldWidth, done.defaultHeight, tile::setDomainB);
        resolution = new TextFieldWidget(minecraft.fontRenderer, ++id, guiX + 3, guiY + 60 + 3, fieldWidth, "");
        rgba = new ColorTextField(this, ++id, minecraft.fontRenderer, guiX + 3, guiY + 75 + 3, fieldWidth);
        tex = new TextFieldWidget(minecraft.fontRenderer, ++id, guiX + 3, guiY + 90 + 3, fieldWidth, "");
        tileCount = new TextFieldWidget(minecraft.fontRenderer, ++id, guiX + 3, guiY + 105 + 3, fieldWidth, "");
        cropToRange = new TextFieldWidget(minecraft.fontRenderer, ++id, guiX + 3, guiY + 120 + 3, fieldWidth, "");
        discThresh = new DiscContinutityTextField(this, ++id, minecraft.fontRenderer, guiX + 3, guiY + 135 + 3, fieldWidth, done.defaultHeight);
        scale = new Vec3dTextField("Scale", this, ++id, minecraft.fontRenderer, guiX + 3, guiY + 150 + 3, fieldWidth, done.defaultHeight, vec -> tile.scale = vec);
        translation = new Vec3dTextField("Translation", this, ++id, minecraft.fontRenderer, guiX + 3, guiY + 165 + 3, fieldWidth, done.defaultHeight, vec -> tile.translation = vec);
        rotation = new Vec3dTextField("Rotation", this, ++id, minecraft.fontRenderer, guiX + 3, guiY + 180 + 3, fieldWidth, done.defaultHeight, vec -> tile.rotation = vec);
        collision = new TextFieldWidget(minecraft.fontRenderer, ++id, guiX + 3, guiY + 195 + 3, fieldWidth, "");

        piO4 = new TextFieldWidget(minecraft.fontRenderer, ++id, guiX + guiWidth - 33, guiY + 15 + 3, 30, "");
        piO2 = new TextFieldWidget(minecraft.fontRenderer, ++id, guiX + guiWidth - 33, guiY + 30 + 3, 30, "");
        pi = new TextFieldWidget(minecraft.fontRenderer, ++id, guiX + guiWidth - 33, guiY + 45 + 3, 30, "");
        pi2 = new TextFieldWidget(minecraft.fontRenderer, ++id, guiX + guiWidth - 33, guiY + 60 + 3, 30, "");
        pi4 = new TextFieldWidget(minecraft.fontRenderer, ++id, guiX + guiWidth - 33, guiY + 75 + 3, 30, "");
        eO2 = new TextFieldWidget(minecraft.fontRenderer, ++id, guiX + guiWidth - 33, guiY + 90 + 3, 30, "");
        e = new TextFieldWidget(minecraft.fontRenderer, ++id, guiX + guiWidth - 33, guiY + 105 + 3, 30, "");
        e2 = new TextFieldWidget(minecraft.fontRenderer, ++id, guiX + guiWidth - 33, guiY + 120 + 3, 30, "");

        spawnSection = new Section(guiX + fieldWidth + 6, guiY + 15 + 2, piO4.x - 3 - guiX - fieldWidth - 6, 117);
        deleteSection = new Section(guiX + guiWidth - 20 - 3, guiY + guiHeight - 20 - 3, 20, 20);

        int tempX = 3;
        int tempY = 3;
        int tempPage = 0;
        for (Evaluation current : Evaluations.ordered) {
            if (current == null)
                continue;
            EvalInfo info = Evaluations.infoMap.get(current);
            if (info == null)
                continue;
            BlockSpawner spawn = new BlockSpawner(id++, 0, 0, info.string, info.slots, info.eval, this, info.rgb[0], info.rgb[1], info.rgb[2])
                    .setOnPage(true);
            ExpressionBlock block = spawn.spawn(id++);
            block.arrange(0, 0);
            if (spawnSection.x + tempX + block.getWidth() + 3 > spawnSection.right) {
                tempX = 3;
                tempY = tempY + block.getHeight() + 3;
            }
            if (spawnSection.y + tempY + block.getHeight() + 3 >= spawnSection.down) {
                tempY = 3;
                tempPage++;
            }
            spawn.setPage(tempPage);
            spawn.x = spawnSection.x + tempX;
            spawn.y = spawnSection.y + tempY;
            block.arrange(spawnSection.x + tempX, spawnSection.y + tempY);
            block.page = spawn.page;
            if (block.page != 0)
                block.visible = false;
            tempX = tempX + block.getWidth() + 3;
        }
        maxPage = tempPage;

        if (tile.getFunction() != null) {
            ExpressionBlock tempBlock = ExpressionBlock.blockFromExpression(id++, tile.getFunction(), this);
            id = tempBlock.gennedID;
            tempBlock.arrange(guiX + 3, blockSpawnY + 3);
            tempBlock.setMoved(true);
        }

        valField = new TextFieldWidget(minecraft.fontRenderer, ++id, spawnSection.x + (spawnSection.width / 2) - 15, spawnSection.down + 3, 30, "");

        next = new TextButton(++id, valField.x + valField.getWidth() + 3, valField.y, font.getStringWidth(NEXT), font.FONT_HEIGHT, NEXT, () -> changePage(1));
        prev = new TextButton(++id, valField.x - font.getStringWidth(PREV) - 3, valField.y, font.getStringWidth(PREV),
                font.FONT_HEIGHT, PREV, () -> changePage(-1));
        undelete = new TextButton(++id, (int) (valField.x + (0.5 * valField.getWidth()) - (0.5 * font.getStringWidth(UNDELETE))),
                valField.y + 14, font.getStringWidth(UNDELETE), font.FONT_HEIGHT, UNDELETE, this::unDeleteBlock);

        done.visible = true;
        next.visible = true;
        prev.visible = true;
        undelete.visible = true;

        fieldToString.put(function, FUNCTION);
        fieldToString.put(domainA, DOMAINA);
        fieldToString.put(domainB, DOMAINB);
        fieldToString.put(range, RANGE);
        fieldToString.put(resolution, RESOLUTION);
        fieldToString.put(scale, SCALE);
        fieldToString.put(tex, TEX);
        fieldToString.put(rgba, RGBA);
        fieldToString.put(cropToRange, CROP);
        fieldToString.put(discThresh, DISCTHRESH);
        fieldToString.put(tileCount, TILECOUNT);
        fieldToString.put(translation, TRANSLATION);
        fieldToString.put(rotation, ROTATION);
        fieldToString.put(valField, VAL);
        fieldToString.put(collision, COLLISION);

        fieldToString.put(piO4, PIO4);
        fieldToString.put(piO2, PIO2);
        fieldToString.put(pi, PI);
        fieldToString.put(pi2, PI2);
        fieldToString.put(pi4, PI4);
        fieldToString.put(eO2, EO2);
        fieldToString.put(e, E);
        fieldToString.put(e2, E2);

        textFields = new TextFieldWidget[]{};
        textFields = ArrayUtils.add(textFields, function);
        textFields = ArrayUtils.add(textFields, domainA);
        textFields = ArrayUtils.add(textFields, range);
        textFields = ArrayUtils.add(textFields, domainB);
        textFields = ArrayUtils.add(textFields, resolution);
        textFields = ArrayUtils.add(textFields, rgba);
        textFields = ArrayUtils.add(textFields, tex);
        textFields = ArrayUtils.add(textFields, tileCount);
        textFields = ArrayUtils.add(textFields, cropToRange);
        textFields = ArrayUtils.add(textFields, discThresh);
        textFields = ArrayUtils.add(textFields, scale);
        textFields = ArrayUtils.add(textFields, translation);
        textFields = ArrayUtils.add(textFields, rotation);
        textFields = ArrayUtils.add(textFields, valField);
        textFields = ArrayUtils.add(textFields, collision);

        textFields = ArrayUtils.add(textFields, piO4);
        textFields = ArrayUtils.add(textFields, piO2);
        textFields = ArrayUtils.add(textFields, pi);
        textFields = ArrayUtils.add(textFields, pi2);
        textFields = ArrayUtils.add(textFields, pi4);
        textFields = ArrayUtils.add(textFields, eO2);
        textFields = ArrayUtils.add(textFields, e);
        textFields = ArrayUtils.add(textFields, e2);

        for (TextFieldWidget field : textFields) {
            field.setVisible(true);
            field.setMaxStringLength(1500);
        }

        if (tile.isErrored())
            function.setText(tile.getErroredFunction());
        if (tile.getFunction() != null) function.setText(tile.getFunction().writeToString());

        f.setMaximumFractionDigits(ConfigVars.GraphingConfigs.decPlaces);

        domainA.setText(format(f, tile.getDomainA()));
        domainB.setText(format(f, tile.getDomainB()));
        range.setText(format(f, tile.getRange()));

        resolution.setText(f.format(tile.getResolution()));
        scale.setText(format(f, tile.scale));
        tex.setText(tile.tex);
        rgba.setText(tile.rgba[0] + " " + tile.rgba[1] + " " + tile.rgba[2] + " " + tile.rgba[3] + " " + tile.colorSlope + " " + tile.rgba[4]);
        cropToRange.setText("" + tile.cropToRange());
        discThresh.setText(f.format(tile.getDiscThresh()) + " " + f.format(tile.getAggDiscThresh()));
        tileCount.setText("" + tile.tileCount);
        translation.setText(format(f, tile.translation));
        rotation.setText(format(f, tile.rotation.scale(180 / Math.PI)));
        collision.setText("" + tile.collision);

        piO4.setText(f.format(Math.PI / 4));
        piO2.setText(f.format(Math.PI / 2));
        pi.setText(f.format(Math.PI));
        pi2.setText(f.format(2 * Math.PI));
        pi4.setText(f.format(4 * Math.PI));
        eO2.setText(f.format(Math.E / 2));
        e.setText(f.format(Math.E));
        e2.setText(f.format(2 * Math.E));

        valField.setText("");

        domainA.setCursorPosition(0);
        domainB.setCursorPosition(0);
        tex.setCursorPosition(0);

        piO4.setCursorPosition(0);
        piO2.setCursorPosition(0);
        pi.setCursorPosition(0);
        pi2.setCursorPosition(0);
        pi4.setCursorPosition(0);
        eO2.setCursorPosition(0);
        e.setCursorPosition(0);
        e2.setCursorPosition(0);

        function.setFocused2(true);

        addButton(done);
        addButton(next);
        addButton(prev);
        addButton(undelete);

        updateBlockStrings();
    }

    private static String format(NumberFormat f, Domain domain) {
        return f.format(domain.min()) + " " + f.format(domain.max());
    }

    private static String format(NumberFormat f, Vec3d vec3d) {
        return f.format(vec3d.x) + " " + f.format(vec3d.y) + f.format(vec3d.z);
    }

        @Override
    public void render(int mouseX, int mouseY, float renderPartials) {
        modified = false;
        background.draw();
        spawnSection.drawSection(40, 40, 40);
        deleteSection.drawSection(255, 0, 0);
        for (TextFieldWidget field : textFields) {
            field.render(mouseX, mouseY, renderPartials);
        }

        for (Widget current : buttons) {
            current.render(mouseX, mouseY, renderPartials);
        }

        if (tile.isErrored()) {
            minecraft.fontRenderer.drawSplitString("Error: " + tile.getErrorMessage(), guiX + 3,
                    guiY + guiHeight - 1 - (minecraft.fontRenderer.getWordWrappedHeight("Error: " + tile.getErrorMessage(), guiWidth - deleteSection.width - 9)),
                    guiWidth - deleteSection.width - 9, 0xFF0000);
            TextFieldWidget erroredField = textFields[erroredBox];
            Section sec = new Section(erroredField.x, erroredField.y, erroredField.getWidth(), erroredField.getHeight());
            sec.drawSection(255, 0, 0, 100);
        }

        if (dragging) draggedBlock.render(mouseX, mouseY, renderPartials);

        for (TextFieldWidget current : textFields) {
            if (dragging)
                break;
            if (mouseX > current.x + current.getWidth() - 10 && mouseX < current.x + current.getWidth() && mouseY > current.y && mouseY < current.y + current.getHeight()) {
                minecraft.currentScreen.drawString(font, fieldToString.get(current), current.x + current.getWidth(), current.y + current.getHeight(), 0);
            }
        }

        for (Widget current : buttons) {
            if (dragging)
                break;
            if (current instanceof ExpressionBlock) {
                ExpressionBlock block = (ExpressionBlock) current;

                if (block.whole(mouseX, mouseY) && !block.moved && block.visible) {
                    minecraft.currentScreen.drawString(font, Evaluations.infoMap.get(block.expression.evaluation).tooltip, guiX - 7,
                            rotation.y + rotation.getHeight() + 15 + 5, 0);
                }
            }
        }

        if (deleteSection.isPointWithinIncl(mouseX, mouseY))
            minecraft.currentScreen.drawString(font, DELETE_SECTION, deleteSection.x, deleteSection.y, 0);
    }

    @Override
    public void tick() {
        Arrays.stream(textFields).forEach(TextFieldWidget::tick);
    }

    private void changePage(int delta) {
        pageInd += delta;

        if (pageInd > maxPage) {
            pageInd = 0;
        }
        if (pageInd < 0) {
            pageInd = maxPage;
        }

        updateExpressionBlockVisibility();
    }

    private void updateExpressionBlockVisibility() {
        for (Widget current : buttons) {
            if (current instanceof ExpressionBlock) {
                ExpressionBlock block = (ExpressionBlock) current;
                if (block.onPage) {
                    block.visible = (block.page == pageInd);
                }
            }
        }
    }

    @Override
    public boolean charTyped(char typedChar, int modifiers) {
        super.charTyped(typedChar, modifiers);

        for (Widget field : textFields) {
            field.charTyped(typedChar, modifiers);
        }

        return true;
    }

    @Override
    public boolean keyPressed(int keyCode, int scanCode, int modifiers) {
        super.keyPressed(keyCode, scanCode, modifiers);

        for (Widget field : textFields) {
            field.keyPressed(keyCode, scanCode, modifiers);
        }

        if (Screen.hasShiftDown()) {
            if (keyCode == 15) // tab
            {
                backOne();
            } else if (keyCode == 208) // down
            {
                forwardOne();
                forwardOne();
                forwardOne();
            } else if (keyCode == 200) // up
            {
                backOne();
                backOne();
                backOne();
            }
        } else if (Screen.hasAltDown()) {
            switch (keyCode) {
                case 203: // left
                    skipInTextField(-4);
                    break;
                case 205: // right
                    skipInTextField(4);
                    break;
            }
        } else if (keyCode == 15 || keyCode == 208) { // tab || down arrow
            forwardOne();
        } else if (keyCode == 200) { // up arrow
            backOne();
        } else if (keyCode == 28) { // enter
            done();
        } else if (keyCode == 19) { // r
            unDeleteBlock();
        }

        return true;
    }

    @Override
    public boolean mouseClicked(double mouseX, double mouseY, int mouseButton) {
        if (Screen.hasShiftDown()) {
            ExpressionBlock block = this.getBlockAt(mouseX, mouseY, true);
            if (block == null)
                return true;
            if (block.slots.length == 0 && block.expression.evaluation == Evaluations.VAL) {
                Scanner boxScan = new Scanner(valField.getText());
                if (boxScan.hasNextDouble()) {
                    block.expression.setValueValue("" + boxScan.nextDouble(), false);
                } else if (boxScan.hasNext()) {
                    block.expression.setValueValue(boxScan.next(), true);
                }

                block.setMessage(block.expression.getValueValue());
                block.arrange(block.x, block.y);
                boxScan.close();
            }

            return true;
        } else if (Screen.hasControlDown() && !dragging) {
            ExpressionBlock clickedBlock = this.getBlockAt(mouseX, mouseY, true);
            if (clickedBlock == null)
                return false;
            ExpressionBlock dupedBlock = clickedBlock.duplicate(id++);
            id = clickedBlock.gennedID;
            dupedBlock.arrange(guiX + 3, 195 + 3);
            dupedBlock.setMoved(true);
            this.setDragging(dupedBlock);
            return true;
        } else if (Screen.hasAltDown() && !dragging) {
            ExpressionBlock clickedBlock = this.getBlockAt(mouseX, mouseY, true);
            if (clickedBlock == null || spawnSection.isPointWithinIncl(mouseX, mouseY))
                return false;
            deleteBlock(clickedBlock);
            return true;
        }

        return Arrays.stream(textFields).map(field -> field.mouseClicked(mouseX, mouseY, mouseButton)).filter(a -> a).findFirst().orElseGet(() -> super.mouseClicked(mouseX, mouseY, mouseButton));
    }

    public void backOne() {
        for (int i = 0; i < textFields.length; i++)
            if (textFields[i].isFocused()) {
                textFields[i].setFocused2(false);
                if (i - 1 >= 0)
                    textFields[i - 1].setFocused2(true);
                else
                    textFields[textFields.length - 1].setFocused2(true);
                break;
            }

    }

    public void forwardOne() {
        for (int i = 0; i < textFields.length; i++)
            if (textFields[i].isFocused()) {
                textFields[i].setFocused2(false);
                if (i + 1 < textFields.length)
                    textFields[i + 1].setFocused2(true);
                else
                    textFields[0].setFocused2(true);
                break;
            }

    }

    public void skipInTextField(int chars) {
        for (TextFieldWidget textField : textFields) {
            if (textField.isFocused()) {
                textField.setCursorPosition(textField.getCursorPosition() + chars);
                break;
            }
        }
    }

    public void done() {
        int box = 0;
        try {
            tile.setErrored(false);
            tile.renderReady = false;
            expression = Expression.parseFromChars(function.getText());
            tile.setFunctionText(function.getText());
            ExpressionBlock block = null;
            if (unslottetBlockCount() > 1)
                setErrored("Loose equation blocks. Reduce the function to a single block.");
            block = this.getFunctionExpression();
            if (block != null) {
                tile.setFunction(block.getExpression());
            } else {
                tile.setFunction(expression);
            }
            box++;
            domainA.done();
            box++;
            range.done();
            box++;
            domainB.done();
            box++;
            tile.setResolution((float) Double.parseDouble(resolution.getText().replaceAll(",", "")));
            box++;
            rgba.done();
            box++;
            tile.tex = tex.getText();
            box++;
            tile.tileCount = Math.max(Integer.parseInt(tileCount.getText().replaceAll(",", "")), 1);
            box++;
            tile.cropToRange(Boolean.parseBoolean(cropToRange.getText()));
            box++;
            discThresh.done();
            box++;
            scale.done();
            box++;
            translation.done();
            box++;
            rotation.done();
            box++;
            tile.collision = Boolean.parseBoolean(collision.getText());
            box++;

            tile.genMesh();
            minecraft.displayGuiScreen(null);

            GCPacketHandler.GRAPH_SYNC.sendToServer(new PacketGC(tile));
        } catch (NumberFormatException e) {
            tile.setErrored(true, "Invalid number formatting. Field #" + box);
            erroredBox = box;
            tile.setErroredFunction(function.getText());
            e.printStackTrace();
        } catch (InputMismatchException e) {
            tile.setErrored(true, "Invalid boolean. Field #" + box);
            erroredBox = box;
            tile.setErroredFunction(function.getText());
            e.printStackTrace();
        } catch (GuiParseException e) {
            tile.setErrored(true, tile.getErrorMessage() + " Field #" + box);
            erroredBox = box;
            tile.setErroredFunction(function.getText());
            e.printStackTrace();
        }
    }

    public void button(Button button) {
        buttons.add(button);
        children.add(button);
    }

    public void setDragging(ExpressionBlock block) {
        if (!modified) {
            if (dragging)
                return;
            dragging = true;
            draggedBlock = block;
            draggedBlock.dragged = true;
            draggedBlock.onPage = false;
            modified = true;
        }
    }

    public void blockDropped() {
        if (!modified) {
            if (spawnSection.isPointWithinIncl(draggedBlock.x, draggedBlock.y))
                return;
            dragging = false;
            draggedBlock.dragged = false;
            if (deleteSection.isPointWithinIncl(draggedBlock.x, draggedBlock.y))
                deleteBlock(draggedBlock);
            draggedBlock = null;
            modified = true;
        }
    }

    public void updateBlockStrings() {
        ExpressionBlock block = this.getFunctionExpression();
        if (block == null)
            return;
        Expression expr = block.getExpression();
        if (expr == null)
            return;

        expr.prepareSeries();

        for (int i = 0; i < buttons.size(); i++) {
            if (buttons.get(i) instanceof ExpressionBlock) {
                ExpressionBlock b = ((ExpressionBlock) buttons.get(i));
                b.updateStringVars();
            }
        }
    }

    public boolean isSlotAt(int x, int y) {
        boolean b = false;
        for (int i = 0; i < buttons.size(); i++) {
            if (buttons.get(i) instanceof ExpressionBlock) {
                b = ((ExpressionBlock) buttons.get(i)).slotNotWhole(x, y);
                if (b)
                    return true;
            }
        }
        return false;
    }

    public ExpressionBlock getBlockAt(double x, double y, boolean excludeDragged) {
        ExpressionBlock temp = null;
        for (Widget button : buttons) {
            if (button instanceof ExpressionBlock)
                if (((ExpressionBlock) button).wholeNotSlot(x, y) && (button != draggedBlock || !excludeDragged) && button.visible)
                    temp = (ExpressionBlock) button;
        }

        return temp;
    }

    public ExpressionBlock getWholeBlockAt(int x, int y, boolean excludeDragged) {
        ExpressionBlock temp = null;
        for (int i = 0; i < buttons.size(); i++) {
            if (buttons.get(i) instanceof ExpressionBlock)
                if (((ExpressionBlock) buttons.get(i)).whole(x, y) && (buttons.get(i) != draggedBlock || !excludeDragged))
                    temp = (ExpressionBlock) buttons.get(i);
        }
        return temp;
    }

    public boolean slottingReqAt(double x, double y) {
        for (int i = 0; i < buttons.size(); i++) {
            if (buttons.get(i) instanceof ExpressionBlock && buttons.get(i) != draggedBlock) {
                ExpressionBlock block = (ExpressionBlock) buttons.get(i);
                if (!block.slotNotWhole(x, y))
                    continue;
                int s = block.getSlotNumAt(x, y);
                if (!block.slotFull(s)) {
                    block.setBlock(s, draggedBlock);
                    return true;
                }
            }
        }
        return false;
    }

    public ExpressionBlock getFunctionExpression() {
        for (int i = 0; i < buttons.size(); i++) {
            if (buttons.get(i) instanceof ExpressionBlock) {
                ExpressionBlock block = (ExpressionBlock) buttons.get(i);
                if (!block.slotted && block.moved && block.visible)
                    return block;
            }
        }
        return null;
    }

    public void removeButton(Widget button) {
        buttons.remove(button);
    }

    public void setTooltipDrawing(boolean drawing, String tipIn) {
        tooltipDrawing = drawing;
        currentTooltip = tipIn;
    }

    public int unslottetBlockCount() {
        int count = 0;
        for (int i = 0; i < buttons.size(); i++) {
            if (buttons.get(i) instanceof ExpressionBlock) {
                ExpressionBlock block = (ExpressionBlock) buttons.get(i);
                if (!block.slotted && block.moved && block.visible)
                    count++;
            }
        }
        return count;
    }

    public void deleteBlock(ExpressionBlock block) {
        deleteList.add(block);
        block.delete(true);
    }

    public void unDeleteBlock() {
        if (!(deleteList.size() > 0))
            return;
        ExpressionBlock block = deleteList.get(deleteList.size() - 1);
        if (block != null) {
            block.unDelete();
            block.arrange(block.x, block.y);
            block.setMoved(true);
            deleteList.remove(block);
        }
    }

    public void setErrored(String errorMessage) throws GuiParseException {
        tile.setErrored(true, errorMessage);
        throw new GuiParseException(errorMessage);
    }
}
